# Generated by Django 4.2.19 on 2025-03-18 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contact-docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt'])]),
        ),
    ]
